name: Deploy npm package

on:
  push:
      branches: [main]
  workflow_dispatch:

env:
  node-version: "22"

jobs:
  npm:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
      - run: corepack enable

      - name: Check publish status
        id: check
        run: |
          NEXT_VERSION=$(jq -r '.version' < packages/greenbox-data/package.json)
          STATUS=$(curl --write-out '%{http_code}\n' --head --silent --output /dev/null https://registry.npmjs.org/greenbox-data/$NEXT_VERSION)
          echo "status=$STATUS" >> "$GITHUB_OUTPUT"

      - name: Publish if necessary
        if: ${{ steps.check.outputs.status == '404' }}
        run: |
          corepack enable
          yarn workspace greenbox-data install --immutable
          yarn workspace greenbox-data npm publish
        env:
          STATUS: ${{ steps.check.outputs.status }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  # jsr:
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: read
  #     id-token: write

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Publish package
  #       run: |
  #         cd packages/greenbox-data
  #         npx jsr publish

        